#! /usr/bin/env python3

from pathlib import Path
import sys

metazephyr = Path.cwd()

if metazephyr.name != "meta-zephyr":
    print("Not running inside meta-zephyr")
    sys.exit(1)

# All machine configurations
machines = metazephyr.glob("meta-zephyr-bsp/conf/machine/*.conf")
machines = set(p.stem for p in machines)

# All kas files
kas = metazephyr.glob("ci/*.yml")
kas = set(p.stem for p in kas)

missing = machines - kas
print(f"The following machines are missing: {', '.join(sorted(missing))}.")

covered = len(machines) - len(missing)
total = len(machines)
percent = int(covered / total * 100)
print(f"Coverage: {percent}%")
